spring.application.name=Proj-04_Movie_Streaming_Home_Page_Data_Rendering


#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp