spring.application.name=BootMVCProj01-FirstApp

# Embedded server port (default is port)
server.port=4041

#ViewResolver inputs (prefix,suffix) for default innternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp