spring.application.name=BootMVCProj02-FirstApp


#Embedded server port (default is 8080)
server.port=4142

#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp