spring.application.name=Proj-16_Multi-Language_Login_Page


#Configure the base file name
spring.messages.basename=message

#View resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#Embedded server port
server.port=8082

#context path
server.servlet.context-path=/MVCProj16