spring.application.name=Proj-01_Display_a_Message_using_Spring_Boot_MVC_and_JSP


#Embedded server port (default is 8080)
server.port=4040

#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp