spring.application.name=Proj-02_Display_Multiple_Messages_using_List


#Embedded server port (default is 8080)
server.port=4242

#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp