spring.application.name=Proj-06_Bank_Account_Summary_Page_Data_Rendering


#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp