spring.application.name=Proj-07_Employee_Salary_Calculator-DataBindingandRendering

#Embedded server port (default is 8080)
server.port=4242

#ViewResolver inputs (prefix,suffix) for default InternalResourceViewResolver
spring.mvc.view.prefix=/WEB-INF/View/
spring.mvc.view.suffix=.jsp